export const skillTiers: Record<string, "Advanced" | "Intermediate" | "Fundamental"> = {
    // -------------------- Advanced --------------------
    "Dynamic Programming": "Advanced",
    "Union Find": "Advanced",
    "Disjoint Set Union": "Advanced",
    "Backtracking": "Advanced",
    "Bitmask DP": "Advanced",
    "Segment Tree": "Advanced",
    "Fenwick Tree": "Advanced",
    "Heavy-Light Decomposition": "Advanced",
    "Suffix Array": "Advanced",
    "Suffix Automaton": "Advanced",
    "Mo's Algorithm": "Advanced",
    "Convex Hull": "Advanced",
    "Max Flow": "Advanced",
    "Min Cost Max Flow": "Advanced",
    "Li Chao Tree": "Advanced",
    "Centroid Decomposition": "Advanced",
    "Divide and Conquer Optimization": "Advanced",
    "Dynamic Connectivity": "Advanced",
    "Persistent Data Structures": "Advanced",

    // -------------------- Intermediate --------------------
    "Hash Table": "Intermediate",
    "Depth-First Search": "Intermediate",
    "Breadth-First Search": "Intermediate",
    "Binary Search": "Intermediate",
    "Two Pointers": "Intermediate",
    "Sliding Window": "Intermediate",
    "Prefix Sum": "Intermediate",
    "Graph": "Intermediate",
    "Tree": "Intermediate",
    "Topological Sort": "Intermediate",
    "Greedy": "Intermediate",
    "Math": "Intermediate",
    "Number Theory": "Intermediate",
    "Combinatorics": "Intermediate",
    "Probability": "Intermediate",
    "Geometry": "Intermediate",
    "Matrix": "Intermediate",
    "Bit Manipulation": "Intermediate",
    "Shortest Path": "Intermediate",
    "Dijkstra": "Intermediate",
    "Bellman-Ford": "Intermediate",
    "Floyd-Warshall": "Intermediate",
    "Strongly Connected Components": "Intermediate",
    "Kruskal": "Intermediate",
    "Prim": "Intermediate",

    // -------------------- Fundamental --------------------
    "Array": "Fundamental",
    "String": "Fundamental",
    "Sorting": "Fundamental",
    "Stack": "Fundamental",
    "Queue": "Fundamental",
    "Deque": "Fundamental",
    "Set": "Fundamental",
    "Map": "Fundamental",
    "Linked List": "Fundamental",
    "Heap": "Fundamental",
    "Basic Math": "Fundamental",
    "Brute Force": "Fundamental",
    "Simulation": "Fundamental",
    "Counting": "Fundamental",
    "Basic Recursion": "Fundamental",
    "Implementation": "Fundamental",
    "Basic I/O": "Fundamental",
};
